deploy_to_server:
  stage: deploy
  image: ruby:2.7
  script:
    # Setup SSH
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    # Write private SSH key from GitLab CI/CD variable
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa

    # Convert to PEM format if needed
    - echo "Converting key to PEM format..."
    - mv ~/.ssh/id_rsa ~/.ssh/id_rsa_openssh
    - ssh-keygen -p -m PEM -f ~/.ssh/id_rsa_openssh -N "" -q || { echo "Key conversion failed"; exit 1; }
    - mv ~/.ssh/id_rsa_openssh ~/.ssh/id_rsa

    # Ensure the target directory exists on the remote server
    - ssh -o StrictHostKeyChecking=no -p 9022 abc@192.0.2.1 "mkdir -p /path/to/deployment/uat_ssp"

    # Configure Git with user credentials
    - git config --global user.email "your_email@example.com"
    - git config --global user.name "Your Name"
    - git config --global credential.helper store

    # Store GitLab token using CI/CD variable
    - echo "https://$CI_GIT_USERNAME:$GLPAT@git.example.com" > ~/.git-credentials

    # Pull the latest changes
    - ssh -o StrictHostKeyChecking=no -p 9022 abc@192.0.2.1 \
        "cd /path/to/deployment/uat_ssp && git pull https://$CI_GIT_USERNAME:$GLPAT@git.example.com/your-group/uat_ssp.git new-branch"

  tags:
    - deploy-runner
  only:
    - new-branch
